{% set name = "sktools" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftbplus/skprogs/archive/refs/tags/{{ version }}.tar.gz
  sha256: 220f7149557ef92b67c69450f9d7bb514de356b4db1571c5a9f20c9c4f0de79f

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install sktools/ -vv --no-deps

requirements:
  host:
    - pip
    - python
  run:
    - numpy
    - scipy
    - python

test:
  imports:
    - sktools
    - sktools.hsd
    - sktools.calculators
    - sktools.skgen
  commands:
    - pip check
    - skgen --version
    - skdiff --version
    - collectspinw -h
  requires:
    - pip

about:
  home: https://github.com/dftbplus/skprogs
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: |
    Package containing a programs to generate Slater-Koster files for the DFTB-method

extra:
  recipe-maintainers:
    - aradi
    - awvwgk
